sudo: false
language: ruby
before_install:
  - gem install bundler || gem install bundler --version '< 2'
rvm:
  - '1.8.7-p371'
  - '1.9.3-p551'
  - '2.0.0-p648'
  - '2.1.10'
  - '2.2.10'
  - '2.3.8'
  - '2.4.6'
  - '2.5.5'
  - '2.6.3'
  - 'jruby-9.1.9.0'
script: bundle exec rspec
matrix:
  include:
    - env: RUBOCOP=✓
      rvm: '2.6.3'
      script: bundle exec rubocop
    - env: CHECK_RUBIES=✓
      rvm: '2.6.3'
      script: bundle exec travis_check_rubies
